export const FETCH_STATUS = {
  NONE: 'NONE',
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
}

export const ON_GET_CATEGORIES_LOOKUP_REQUEST =
  'ON_GET_CATEGORIES_LOOKUP_REQUEST'
export const ON_GET_CATEGORIES_LOOKUP_SUCCESS =
  'ON_GET_CATEGORIES_LOOKUP_SUCCESS'
export const ON_GET_CATEGORIES_LOOKUP_FAIL = 'ON_GET_CATEGORIES_LOOKUP_FAIL'

export const ON_GET_CATEGORIES_REQUEST = 'ON_GET_CATEGORIES_REQUEST'
export const ON_GET_CATEGORIES_SUCCESS = 'ON_GET_CATEGORIES_SUCCESS'
export const ON_GET_CATEGORIES_FAIL = 'ON_GET_CATEGORIES_FAIL'

export const ON_GET_MOVIE_DETAIL_REQUEST = 'ON_GET_MOVIE_DETAIL_REQUEST'
export const ON_GET_MOVIE_DETAIL_SUCCESS = 'ON_GET_MOVIE_DETAIL_SUCCESS'
export const ON_GET_MOVIE_DETAIL_FAIL = 'ON_GET_MOVIE_DETAIL_FAIL'
