// TestActions

export const ON_GET_CATEGORIES_LOOKUP_REQUEST =
  'ON_GET_CATEGORIES_LOOKUP_REQUEST'
export const ON_GET_CATEGORIES_LOOKUP_SUCCESS =
  'ON_GET_CATEGORIES_LOOKUP_SUCCESS'
export const ON_GET_CATEGORIES_LOOKUP_FAIL = 'ON_GET_CATEGORIES_LOOKUP_FAIL'

export const ON_GET_CATEGORIES_REQUEST = 'ON_GET_CATEGORIES_REQUEST'
export const ON_GET_CATEGORIES_SUCCESS = 'ON_GET_CATEGORIES_SUCCESS'
export const ON_GET_CATEGORIES_FAIL = 'ON_GET_CATEGORIES_FAIL'
